import nodemailer from 'nodemailer';
import twilioClient from 'twilio';
import { eq, and, desc } from 'drizzle-orm';
import { getDb } from '../db/index.js';
import { notifications, users } from '../db/schema/index.js';

// ── Transports ───────────────────────────────────────────────────────────────

function getEmailTransporter() {
  const host = process.env.BREVO_SMTP_HOST;
  const port = Number(process.env.BREVO_SMTP_PORT) || 587;
  const user = process.env.BREVO_SMTP_USER;
  const pass = process.env.BREVO_SMTP_PASS;

  if (!host || !user || !pass) {
    return null; // Not configured
  }

  return nodemailer.createTransport({
    host,
    port,
    secure: false, // true for 465, false for other ports
    auth: { user, pass },
  });
}

function getTwilioClient() {
  const sid = process.env.TWILIO_ACCOUNT_SID;
  const token = process.env.TWILIO_AUTH_TOKEN;
  let from = process.env.TWILIO_WHATSAPP_FROM;

  if (!sid || !token || !from) {
    return null; // Not configured
  }

  if (!from.startsWith('whatsapp:')) {
    from = `whatsapp:${from}`;
  }

  return {
    client: twilioClient(sid, token),
    from,
  };
}

function getHtmlEmailTemplate({ name, title, message }) {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f4f7fa; color: #0f172a; margin: 0; padding: 0; }
        .container { max-width: 580px; margin: 30px auto; background-color: #ffffff; border-radius: 16px; border: 1px solid #e2e8f0; overflow: hidden; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.05); }
        .header { background: linear-gradient(135deg, #0f5f73 0%, #0b4a5a 100%); color: #ffffff; padding: 28px 24px; text-align: center; }
        .header h1 { margin: 0; font-size: 20px; font-weight: 800; letter-spacing: 0.1em; text-transform: uppercase; }
        .content { padding: 32px 28px; line-height: 1.65; }
        .greeting { font-size: 16px; font-weight: 700; color: #0f172a; margin-bottom: 16px; }
        .message { font-size: 15px; color: #334155; margin-bottom: 28px; }
        .footer { background-color: #f8fafc; padding: 20px 24px; text-align: center; border-top: 1px solid #f1f5f9; font-size: 11px; color: #94a3b8; }
        .footer p { margin: 4px 0; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>AssetFlow</h1>
        </div>
        <div class="content">
          <div class="greeting">Hello ${name},</div>
          <div class="message">${message}</div>
        </div>
        <div class="footer">
          <p>This is an automated operational notification generated by AssetFlow.</p>
          <p>&copy; 2026 AssetFlow Systems &middot; Enterprise Portal</p>
        </div>
      </div>
    </body>
    </html>
  `;
}

// ── Notification Core ─────────────────────────────────────────────────────────

/**
 * Creates a notification in the DB and triggers external dispatches (Email/WhatsApp) if config is present.
 */
export async function sendNotification({ userId, title, message, type = 'general' }) {
  const db = getDb();

  // 1. Insert into database
  console.log(`[Notification] Creating in DB for User ${userId}: [${title}] ${message}`);
  const [notif] = await db.insert(notifications).values({
    userId,
    title,
    message,
    type,
    read: false,
  }).returning();

  // 2. Fetch User contact info
  const [user] = await db.select({ email: users.email, name: users.name }).from(users).where(eq(users.id, userId));
  if (!user) return notif;

  // 3. Dispatch Email via Brevo API or SMTP
  const apiKey = process.env.BREVO_API_KEY;
  const emailHtml = getHtmlEmailTemplate({ name: user.name, title, message });

  if (apiKey) {
    const senderEmail = process.env.BREVO_SENDER_EMAIL || 'support.heed@gmail.com';
    const senderName = process.env.BREVO_SENDER_NAME || 'Heed Support';
    
    try {
      const response = await fetch('https://api.brevo.com/v3/smtp/email', {
        method: 'POST',
        headers: {
          'accept': 'application/json',
          'api-key': apiKey,
          'content-type': 'application/json'
        },
        body: JSON.stringify({
          sender: { name: senderName, email: senderEmail },
          to: [{ email: user.email, name: user.name }],
          subject: `AssetFlow Notification: ${title}`,
          htmlContent: emailHtml
        })
      });
      if (response.ok) {
        console.log('[Email] API Dispatch successful');
      } else {
        const errText = await response.text();
        console.error('[Email] API Dispatch failed:', errText);
      }
    } catch (err) {
      console.error('[Email] API Dispatch failed:', err.message);
    }
  } else {
    const transporter = getEmailTransporter();
    if (transporter) {
      const fromEmail = process.env.BREVO_EMAIL_FROM || 'no-reply@assetflow.com';
      const mailOptions = {
        from: `"AssetFlow Notifications" <${fromEmail}>`,
        to: user.email,
        subject: `AssetFlow Notification: ${title}`,
        html: emailHtml,
        text: `Hello ${user.name},\n\nThis is an automated alert from AssetFlow:\n\n${message}\n\nBest regards,\nThe AssetFlow Team`,
      };

      try {
        const info = await transporter.sendMail(mailOptions);
        console.log(`[Email] Dispatch successful: ${info.messageId}`);
      } catch (err) {
        console.error('[Email] Dispatch failed:', err.message);
      }
    } else {
      console.log('[Email] Skip (BREVO_SMTP not fully configured)');
    }
  }

  // 4. Dispatch WhatsApp via Twilio
  const twilio = getTwilioClient();
  let testWhatsAppTo = process.env.TWILIO_WHATSAPP_TO;
  if (twilio && testWhatsAppTo) {
    if (!testWhatsAppTo.startsWith('whatsapp:')) {
      testWhatsAppTo = `whatsapp:${testWhatsAppTo}`;
    }
    const whatsappBody = `💼 *ASSETFLOW ENTERPRISE ALERT*\n\n*Subject:* ${title.toUpperCase()}\n\n*Operational Details:*\n${message}\n\n*System:* http://localhost:5173/dashboard\n*Timestamp:* ${new Date().toLocaleString()}`;

    try {
      const msg = await twilio.client.messages.create({
        body: whatsappBody,
        from: twilio.from,
        to: testWhatsAppTo,
      });
      console.log(`[WhatsApp] Dispatch successful: ${msg.sid}`);
    } catch (err) {
      console.error('[WhatsApp] Dispatch failed:', err.message);
    }
  } else {
    console.log('[WhatsApp] Skip (TWILIO_WHATSAPP not fully configured)');
  }

  return notif;
}

// ── API Service Functions ─────────────────────────────────────────────────────

export async function listUserNotifications(userId, { limit = 50, offset = 0 } = {}) {
  const db = getDb();
  return db
    .select()
    .from(notifications)
    .where(eq(notifications.userId, userId))
    .orderBy(desc(notifications.createdAt))
    .limit(limit)
    .offset(offset);
}

export async function markNotificationAsRead(id, userId) {
  const db = getDb();
  const [updated] = await db
    .update(notifications)
    .set({ read: true })
    .where(and(eq(notifications.id, id), eq(notifications.userId, userId)))
    .returning();

  if (!updated) {
    const error = new Error('Notification not found or unauthorized.');
    error.statusCode = 404;
    throw error;
  }
  return updated;
}

export async function markAllNotificationsRead(userId) {
  const db = getDb();
  await db
    .update(notifications)
    .set({ read: true })
    .where(and(eq(notifications.userId, userId), eq(notifications.read, false)));
  return { success: true };
}
